version: '3'
services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis:latest
  server:
    depends_on:
      - mysqldb
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_USER=root
      - MYSQL_HOST=mysqldb
      - MYSQL_DATABASE=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./server:/app