version: "3"
services:
  client:
    image: "binuraen/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "binuraen/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_PORT=$MYSQL_PORT
  worker:
    image: "binuraen/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "binuraen/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
