name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t binuraen/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true binuraen/react-test npm test

      - run: docker build -t binuraen/multi-client ./client
      - run: docker build -t binuraen/multi-nginx ./nginx
      - run: docker build -t binuraen/multi-server ./server
      - run: docker build -t binuraen/multi-worker ./worker

      - run: docker push binuraen/multi-client
      - run: docker push binuraen/multi-nginx
      - run: docker push binuraen/multi-server
      - run: docker push binuraen/multi-worker
